name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['backend/**']

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: asterism-api
      IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/asterism:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          envs: IMAGE_TAG
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          key: ${{ secrets.VPS_SSH_KEY }}
          username: root
          envs: APP_NAME,IMAGE_TAG
          script: |
            docker pull $IMAGE_TAG
            docker stop $APP_NAME || true
            docker rm $APP_NAME || true
            docker run -d \
              --name $APP_NAME \
              -p 80:8080 \
              -e DATABASE_URL=${{ secrets.SUPABASE_URL }} \
              $IMAGE_TAG
            docker image prune -f